# Generated by Django 3.2.9 on 2021-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_write_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='write',
            name='mood',
            field=models.CharField(choices=[('Good', 'Good'), ('Soso', 'Soso'), ('Bad', 'Bad')], default='Good', max_length=4, verbose_name='기분'),
        ),
    ]
