# Generated by Django 3.2.9 on 2021-12-07 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('genre', models.CharField(choices=[('만화', 'Comic'), ('소설', 'Novel')], default='만화', max_length=10, verbose_name='장르')),
                ('author', models.CharField(db_index=True, max_length=20, verbose_name='작가')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='제목')),
                ('buy', models.BooleanField(verbose_name='소장')),
                ('content', models.TextField(verbose_name='감상')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
            ],
            options={
                'verbose_name': '독후감',
                'verbose_name_plural': '독후감 목록',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('photo', models.ImageField(upload_to='', verbose_name='사진')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '프로필',
                'verbose_name_plural': '프로필',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='태그')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=20, verbose_name='작성자')),
                ('message', models.TextField(verbose_name='내용')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='연관글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
            },
        ),
    ]
