# Generated by Django 3.2.9 on 2021-12-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='title',
            field=models.CharField(default=True, max_length=100, verbose_name='제목'),
        ),
    ]
