# Generated by Django 3.2.10 on 2021-12-13 02:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('description', models.TextField(verbose_name='메뉴설명')),
                ('photo', models.ImageField(upload_to='shop/menu/%y/%m/%d', verbose_name='메뉴사진')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴목록',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='태그')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그목록',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='가게명')),
                ('description', models.TextField(verbose_name='가게정보')),
                ('telephone', models.CharField(help_text='입력예) 042-1234-1234', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{4}-?\\d{4}-?\\d{4}$', message='전화번호를 입력해주세요.')], verbose_name='전화번호')),
                ('photo', models.ImageField(upload_to='shop/photo/%y/%m/%d', verbose_name='사진')),
                ('menu_set', models.ManyToManyField(blank=True, to='shop.Menu')),
                ('tag_set', models.ManyToManyField(blank=True, to='shop.Tag')),
            ],
            options={
                'verbose_name': '가게',
                'verbose_name_plural': '가게목록',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('author_name', models.CharField(max_length=20, verbose_name='작성자')),
                ('reorder', models.BooleanField(null=True, verbose_name='재주문의사')),
                ('message', models.TextField(verbose_name='리뷰내용')),
                ('photo', models.ImageField(blank=True, upload_to='shop/review/%y/%m/%d', verbose_name='리뷰사진')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰목록',
            },
        ),
    ]
