# Generated by Django 3.2.10 on 2021-12-10 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('description', models.TextField(verbose_name='메뉴설명')),
                ('photo', models.ImageField(upload_to='shop/menu/%y/%m/%d', verbose_name='메뉴사진')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴목록',
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '리뷰', 'verbose_name_plural': '리뷰목록'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '가게', 'verbose_name_plural': '가게목록'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그목록'},
        ),
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shop/review/%y/%m/%d', verbose_name='리뷰사진'),
        ),
        migrations.AddField(
            model_name='review',
            name='reorder',
            field=models.BooleanField(null=True, verbose_name='재주문의사'),
        ),
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(default='photo', upload_to='shop/photo/%y/%m/%d', verbose_name='사진'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(max_length=20, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(verbose_name='리뷰내용'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(verbose_name='가게정보'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='가게명'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telephone',
            field=models.CharField(help_text='입력예) 042-1234-1234', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}-?\\d{4}-?\\d{4}$', message='전화번호를 입력해주세요.')], verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='태그'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정시간'),
        ),
        migrations.AddField(
            model_name='shop',
            name='menu_set',
            field=models.ManyToManyField(blank=True, to='shop.Menu'),
        ),
    ]
