# Generated by Django 3.2.10 on 2021-12-14 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('category', models.CharField(choices=[('만화', 'Comic'), ('소설', 'Novel'), ('웹소설', 'Webnovel'), ('웹툰', 'Webtoon')], max_length=10, verbose_name='장르')),
                ('author_name', models.CharField(max_length=100, verbose_name='작가')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('photo', models.ImageField(upload_to='blog/post/%y/%m/%d', verbose_name='사진')),
                ('description', models.TextField(verbose_name='내용')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='태그')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('author_name', models.CharField(max_length=100, verbose_name='작성자')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('photo', models.ImageField(blank=True, upload_to='blog/review/%y/%m/%d', verbose_name='사진')),
                ('description', models.TextField(verbose_name='내용')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='작품')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='태그목록'),
        ),
    ]
