# Generated by Django 3.2.9 on 2021-11-30 11:14

import book_report.upload_to
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=20, verbose_name='작가 이름')),
                ('book_name', models.CharField(max_length=100, verbose_name='책 제목')),
                ('content', models.TextField(verbose_name='감상문')),
                ('photo', models.ImageField(blank=True, upload_to=book_report.upload_to.uuid_name_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
