# Generated by Django 3.2.9 on 2021-11-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0002_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('만화', 'Comics'), ('웹툰', 'Webtoon'), ('소설', 'Novel'), ('수필', 'Essay'), ('시', 'Poem')], default='만화', max_length=2, verbose_name='장르'),
        ),
    ]
