# Generated by Django 3.2.9 on 2021-11-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0003_alter_post_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(choices=[('만화', '만화'), ('웹툰', '웹툰'), ('소설', '소설'), ('수필', '수필'), ('시', '시')], default='만화', max_length=2, verbose_name='장르'),
        ),
    ]
