# Generated by Django 3.2.9 on 2021-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_report', '0006_auto_20211130_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(verbose_name='작성 시간'),
        ),
    ]
